### ISSUE TITLE
Unable to edit dokie.li documents properly with node-solid-server

### ISSUE THREAD

**Issue by jakubklimek** [solid/solid#139]
I am not sure whether this is a solid issue or dokie.li issue:
When I start at https://dokie.li, login with [my WebID](https://jakub.solid.opendata.cz/profile/card#me), click ```New``` or ```Save As```, browse to ```/public/papers``` and save the paper there, in both cases, the HTML is saved in my solid instance. However, then I get redirected there and see errors and cannot edit using dokie.li (only in html editor):
```
Outline.expand: Unable to fetch <https://jakub.solid.opendata.cz//public/papers/05d6cf84-6478-4f8d-a964-c6731077c630?author=true>: Failed to load  <https://jakub.solid.opendata.cz//public/papers/05d6cf84-6478-4f8d-a964-c6731077c630?author=true> Fetcher: Error trying to parse <https://jakub.solid.opendata.cz//public/papers/05d6cf84-6478-4f8d-a964-c6731077c630?author=true> as Notation3:
Error: Error: NamedNode IRI "https://jakub.solid.opendata.cz//public/papers/!DOCTYPE html" must not contain unencoded spaces.:
Error: Error: NamedNode IRI "https://jakub.solid.opendata.cz//public/papers/!DOCTYPE html" must not contain unencoded spaces.
    at new t (https://linkeddata.github.io/mashlib/dist/mashlib.min.js:7:24761)
    at t.value (https://linkeddata.github.io/mashlib/dist/mashlib.min.js:118:59309)
    at e.uri_ref2 (https://linkeddata.github.io/mashlib/dist/mashlib.min.js:7:184771)
    at e.node (https://linkeddata.github.io/mashlib/dist/mashlib.min.js:7:182152)
    at e.nodeOrLiteral (https://linkeddata.github.io/mashlib/dist/mashlib.min.js:7:186973)
    at e.path (https://linkeddata.github.io/mashlib/dist/mashlib.min.js:7:178680)
    at e.item (https://linkeddata.github.io/mashlib/dist/mashlib.min.js:7:178542)
    at e.subject (https://linkeddata.github.io/mashlib/dist/mashlib.min.js:7:177185)
    at e.object (https://linkeddata.github.io/mashlib/dist/mashlib.min.js:7:186676)
    at e.statement (https://linkeddata.github.io/mashlib/dist/mashlib.min.js:7:176999) status: 200
```
![image](https://user-images.githubusercontent.com/718827/39927940-2c9f79e2-5534-11e8-9352-c10714bab779.png)

When I start from the ```node-solid-server``` instance, I go to my public folder, then ```papers``` then I add a dokie.li document like this:
![image](https://user-images.githubusercontent.com/718827/39928019-73f6d75e-5534-11e8-8dce-3d03ad5c0e17.png), it creates a folder with index.html in it. When I choose the dokie.li view, I get an error like this:
```
Outline.expand: Unable to fetch <https://jakub.solid.opendata.cz/public/papers/Paper3/index.html>: Failed to load  <https://jakub.solid.opendata.cz/public/papers/Paper3/index.html> Fetcher: Error trying to parse <https://jakub.solid.opendata.cz/public/papers/Paper3/index.html> as RDFa:
TypeError: Cannot assign to read only property 'baseURI' of object '#<XMLDocument>':
TypeError: Cannot assign to read only property 'baseURI' of object '#<XMLDocument>'
    at value (https://linkeddata.github.io/mashlib/dist/mashlib.min.js:20:35592)
    at t.e (https://linkeddata.github.io/mashlib/dist/mashlib.min.js:20:40848)
    at t.value (https://linkeddata.github.io/mashlib/dist/mashlib.min.js:20:43293)
    at https://linkeddata.github.io/mashlib/dist/mashlib.min.js:20:57816
```
But at least I can edit there.

Not sure if this is the current expected behavior, but it definitely is not very nice to show e.g. to students.

**Comment by kjetilk** [comment]
It seems quite likely that this is fixed on 5.0.0, so it might be worth trying it on https://dev.inrupt.net/ or a fresh install of the beta. You might run into other problems, e.g. #235 , but it would be interesting to hear if this problem is reproducable.
